import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
title="[J] ava [S] ucks"
startup_mode="Maximized"
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.95

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family="Hasklug Nerd Font"
style = "Bold"

[font.bold_italic]
family="Hasklug Nerd Font"
style = "Bold Italic"

[font.italic]
family="Hasklug Nerd Font"
style = "Italic"

[font.normal]
family="Hasklug Nerd Font"
style="Regular"

