# rebind lead key
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

#rebind screen split
bind v split-window -h
bind h split-window -v
unbind '"'
unbind %

set-option -g default-shell /bin/zsh

